FROM php:8.2-apache

# อัปเดตและติดตั้ง dependencies
RUN apt-get update && apt-get install -y \
    libpng-dev libjpeg-dev libfreetype6-dev zip git unzip curl libzip-dev \
    && docker-php-ext-configure zip \
    && docker-php-ext-install pdo pdo_mysql zip

# ติดตั้ง Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# ตั้งค่า Document Root ให้ชี้ที่ public
ENV APACHE_DOCUMENT_ROOT /var/www/html/public

# เปลี่ยนค่าใน Apache config ให้รองรับ Laravel
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf \
 && sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf

# เปิด mod_rewrite และ AllowOverride All (สำคัญมาก)
RUN a2enmod rewrite \
 && sed -i '/<Directory \/var\/www\/>/,/<\/Directory>/ s/AllowOverride None/AllowOverride All/' /etc/apache2/apache2.conf

# คัดลอก Laravel project
COPY . /var/www/html

# ติดตั้ง Laravel dependencies
RUN composer install --no-dev --optimize-autoloader

# ตั้งสิทธิ์ให้ Apache เขียนไฟล์ได้
RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache

RUN ls -la /var/www/html/public/.htaccess

# เปิดพอร์ต 80
EXPOSE 80
